import React, { useState } from "react";

const GEMINI_API_KEY = "YOUR_API_KEY_HERE"; // మీ సొంత free Gemini key ఇక్కడ పెట్టుకోండి (aistudio.google.com)

const initialPosts = [
  { name: "Anusha", category: "Design", caption: "Spent the morning redesigning a dashboard nobody asked for. Worth it.", likes: 120, liked: false, saved: false },
    { name: "Sam Cole", category: "Tech", caption: "Shipped a feature in two days that the roadmap said would take two weeks.", likes: 84, liked: false, saved: false },
      { name: "Nadia Reyes", category: "Travel", caption: "Got lost in Porto for three hours and found the best pastry of my life.", likes: 203, liked: false, saved: false },
      ];

      const candidatePosts = [
        { name: "Marcus Webb", category: "Fitness", caption: "PR'd my deadlift today. My lower back has filed a complaint.", likes: 95, liked: false, saved: false },
          { name: "Chef Rosa", category: "Food", caption: "Burned the garlic, started over, ended up with a better dish.", likes: 150, liked: false, saved: false },
            { name: "Nova Reign", category: "Music", caption: "New track is out. Wrote it in a parking lot at 2am.", likes: 76, liked: false, saved: false },
              { name: "Iris Volkov", category: "Art", caption: "Ruined a painting trying to fix one corner. Starting a new one tomorrow.", likes: 60, liked: false, saved: false },
                { name: "Dr. Yuki Tanaka", category: "Science", caption: "Our experiment failed in a way that's more interesting than if it had worked.", likes: 88, liked: false, saved: false },
                  { name: "Clara Voss", category: "Finance", caption: "Read a 40-page prospectus so you don't have to. You're welcome.", likes: 54, liked: false, saved: false },
                    { name: "Rook Hayes", category: "Gaming", caption: "Beat the final boss on the hardest difficulty after eleven attempts.", likes: 132, liked: false, saved: false },
                      { name: "Kofi Mensah", category: "Travel", caption: "Slept in a train station in Kyoto. Would do it again.", likes: 110, liked: false, saved: false },
                      ];

                      export default function App() {
                        const [posts, setPosts] = useState(initialPosts);
                          const [pool, setPool] = useState(candidatePosts);
                            const [tuning, setTuning] = useState(false);

                              function handleLike(index) {
                                  setPosts(posts.map((post, i) => (i === index ? { ...post, liked: !post.liked } : post)));
                                    }

                                      function handleSave(index) {
                                          setPosts(posts.map((post, i) => (i === index ? { ...post, saved: !post.saved } : post)));
                                            }

                                              function handleDismiss(index) {
                                                  setPosts(posts.filter((post, i) => i !== index));
                                                    }

                                                      function buildProfileSummary() {
                                                          const liked = posts.filter((p) => p.liked).map((p) => p.category);
                                                              const saved = posts.filter((p) => p.saved).map((p) => p.category);
                                                                  if (liked.length === 0 && saved.length === 0) return "No behavior yet. Pick a diverse mix.";
                                                                      return `Liked categories: ${liked.join(", ") || "none"}. Saved categories: ${saved.join(", ") || "none"}.`;
                                                                        }

                                                                          async function tuneFeed() {
                                                                              if (pool.length === 0) return;
                                                                                  setTuning(true);

                                                                                      const candidateList = pool
                                                                                            .map((p, i) => `index:${i} | category:${p.category} | caption:"${p.caption}"`)
                                                                                                  .join("\n");

                                                                                                      const prompt = `You are picking the next posts for a personalized feed.

                                                                                                      User behavior: ${buildProfileSummary()}

                                                                                                      Candidate posts:
                                                                                                      ${candidateList}

                                                                                                      Pick the best 2 posts for this user from the list above. For each, give a short reason (under 10 words).

                                                                                                      Respond with ONLY a JSON array, no other text, no markdown, like this:
                                                                                                      [{"index": 0, "reason": "..."}, {"index": 3, "reason": "..."}]`;

                                                                                                          try {
                                                                                                                const response = await fetch(
                                                                                                                        `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${GEMINI_API_KEY}`,
                                                                                                                                {
                                                                                                                                          method: "POST",
                                                                                                                                                    headers: { "Content-Type": "application/json" },
                                                                                                                                                              body: JSON.stringify({
                                                                                                                                                                          contents: [{ parts: [{ text: prompt }] }],
                                                                                                                                                                                    }),
                                                                                                                                                                                            }
                                                                                                                                                                                                  );
                                                                                                                                                                                                        const data = await response.json();
                                                                                                                                                                                                              const rawText = data.candidates[0].content.parts[0].text;
                                                                                                                                                                                                                    const cleaned = rawText.replace(/```json|```/g, "").trim();
                                                                                                                                                                                                                          const picks = JSON.parse(cleaned);

                                                                                                                                                                                                                                const newPosts = picks.map((pick) => ({ ...pool[pick.index], reason: pick.reason }));
                                                                                                                                                                                                                                      const usedIndexes = picks.map((p) => p.index);
                                                                                                                                                                                                                                            const newPool = pool.filter((p, i) => !usedIndexes.includes(i));

                                                                                                                                                                                                                                                  setPosts([...posts, ...newPosts]);
                                                                                                                                                                                                                                                        setPool(newPool);
                                                                                                                                                                                                                                                            } catch (err) {
                                                                                                                                                                                                                                                                  setPosts([...posts, ...pool.slice(0, 2)]);
                                                                                                                                                                                                                                                                        setPool(pool.slice(2));
                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                setTuning(false);
                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                    const likedCount = posts.filter((p) => p.liked).length;
                                                                                                                                                                                                                                                                                      const savedCount = posts.filter((p) => p.saved).length;
                                                                                                                                                                                                                                                                                        const confidence = Math.min(100, likedCount * 20 + savedCount * 30);

                                                                                                                                                                                                                                                                                          return (
                                                                                                                                                                                                                                                                                              <div style={{ background: "#16141F", minHeight: "100vh", padding: "20px" }}>
                                                                                                                                                                                                                                                                                                    <h1 style={{ color: "#F2A93B" }}>≋ Signal</h1>
                                                                                                                                                                                                                                                                                                          <p style={{ color: "#8B879C", marginBottom: "12px" }}>my AI feed project starts here</p>

                                                                                                                                                                                                                                                                                                                <div style={{ marginBottom: "20px", maxWidth: "400px" }}>
                                                                                                                                                                                                                                                                                                                        <div style={{ background: "#2C2A3B", borderRadius: "8px", height: "8px", overflow: "hidden" }}>
                                                                                                                                                                                                                                                                                                                                  <div style={{ background: "#F2A93B", height: "100%", width: confidence + "%", transition: "width 0.4s ease" }} />
                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                  <p style={{ color: "#8B879C", fontSize: "12px", marginTop: "6px" }}>{confidence}% tuned to you</p>
                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                              {posts.map((post, index) => (
                                                                                                                                                                                                                                                                                                                                                                      <div key={index} style={{ background: "#1F1D2B", borderRadius: "16px", padding: "16px", maxWidth: "400px", marginBottom: "16px" }}>
                                                                                                                                                                                                                                                                                                                                                                                <p style={{ color: "#F3EFE6", fontWeight: "bold", margin: "0 0 4px 0" }}>{post.name}</p>
                                                                                                                                                                                                                                                                                                                                                                                          <p style={{ color: "#8B879C", fontSize: "12px", margin: "0 0 8px 0" }}>{post.category}</p>
                                                                                                                                                                                                                                                                                                                                                                                                    <p style={{ color: "#F3EFE6", margin: "0 0 12px 0" }}>{post.caption}</p>

                                                                                                                                                                                                                                                                                                                                                                                                              {post.reason && (
                                                                                                                                                                                                                                                                                                                                                                                                                          <p style={{ color: "#F2A93B", fontSize: "12px", margin: "0 0 12px 0" }}>⚡ tuned: {post.reason}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                    )}

                                                                                                                                                                                                                                                                                                                                                                                                                                              <div style={{ display: "flex", gap: "16px", alignItems: "center" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button onClick={() => handleLike(index)} style={{ background: "none", border: "none", color: post.liked ? "#F2A93B" : "#8B879C", fontSize: "16px", cursor: "pointer", padding: 0 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ❤ {post.likes + (post.liked ? 1 : 0)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button onClick={() => handleSave(index)} style={{ background: "none", border: "none", color: post.saved ? "#5FD0D9" : "#8B879C", fontSize: "16px", cursor: "pointer", padding: 0 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              🔖 {post.saved ? "Saved" : "Save"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button onClick={() => handleDismiss(index)} style={{ background: "none", border: "none", color: "#8B879C", fontSize: "16px", cursor: "pointer", padding: 0, marginLeft: "auto" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ✕
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ))}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {pool.length > 0 && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onClick={tuneFeed}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          disabled={tuning}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    style={{ background: tuning ? "#2C2A3B" : "#F2A93B", border: "none", color: tuning ? "#8B879C" : "#16141F", fontWeight: "bold", padding: "12px 20px", borderRadius: "10px", cursor: "pointer", maxWidth: "400px", width: "100%" }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {tuning ? "Tuning your feed..." : "Tune feed further"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
